# Generated by Django 5.0.2 on 2024-02-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserv_mest_parkovki',
            name='user',
            field=models.CharField(default='', max_length=50, verbose_name='User'),
        ),
    ]
