# Generated by Django 5.0.2 on 2024-02-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reserv_mest_parkovki_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserv_mest_parkovki',
            name='mesto',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nazvanie'),
        ),
    ]
