# Generated by Django 5.0.2 on 2024-03-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_alter_reserv_mest_parkovki_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserv_mest_parkovki',
            name='user',
            field=models.CharField(default='', max_length=50, verbose_name='User'),
        ),
    ]
